export const weddingImages = {
  homeHero: "/images/wedding/home-hero.jpg",
  homeBannerOne: "/images/wedding/home-banner-1.jpg",
  homeBannerTwo: "/images/wedding/home-banner-2.jpg",
  homeBannerThree: "/images/wedding/home-banner-3.jpg",
  ourStoryHero: "/images/wedding/our-story-hero.jpg",
  travelHero: "/images/wedding/ibadan-mapo-hall.jpg",
  eventsHero: "/images/wedding/events-hero.jpg",
  registryHero: "/images/wedding/gallery-12.jpg",
  rsvpHero: "/images/wedding/rsvp-hero.jpg",
  ogImage: "/images/wedding/og-image.jpg",
  storyFeature: "/images/wedding/story-feature.jpg",
  ibadanMonument: "/images/wedding/ibadan-mapo-hall.jpg",
  eventsEditorialPoster: "/images/wedding/events-editorial-poster.jpg",
  eventsGrandFinale: "/images/wedding/events-grand-finale.jpg",
  eventsCoupleEmbrace: "/images/wedding/events-couple-embrace.jpg",
  eventsBride: "/images/wedding/events-bride.jpg",
  eventsGroom: "/images/wedding/events-groom.jpg",
  featureCards: {
    story: "/images/wedding/feature-story.jpg",
    events: "/images/wedding/feature-events.jpg",
    travel: "/images/wedding/ibadan-mapo-hall.jpg",
    registry: "/images/wedding/feature-registry.jpg",
    rsvp: "/images/wedding/feature-rsvp.jpg",
  },
  gallery: [
    "/images/wedding/gallery-1.jpg",
    "/images/wedding/gallery-2.jpg",
    "/images/wedding/gallery-3.jpg",
    "/images/wedding/gallery-4.jpg",
    "/images/wedding/gallery-5.jpg",
    "/images/wedding/gallery-6.jpg",
    "/images/wedding/gallery-7.jpg",
    "/images/wedding/gallery-8.jpg",
    "/images/wedding/gallery-9.jpg",
    "/images/wedding/gallery-10.jpg",
    "/images/wedding/gallery-11.jpg",
    "/images/wedding/gallery-12.jpg",
    "/images/wedding/gallery-13.jpg",
    "/images/wedding/gallery-14.jpg",
  ],
};
